/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (MailPackageBarcode.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class MailPackageBarcodeBase extends AbstractEntity {

        public function MailPackageBarcodeBase() {
            super();
        }

        private var _bar_type:int;
        private var _barcode:String;
        private var _id:int;
        private var _source:int;

        public function set bar_type(value:int):void {
            _bar_type = value;
        }
        public function get bar_type():int {
            return _bar_type;
        }

        public function set barcode(value:String):void {
            _barcode = value;
        }
        public function get barcode():String {
            return _barcode;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set source(value:int):void {
            _source = value;
        }
        public function get source():int {
            return _source;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _bar_type = input.readObject() as int;
            _barcode = input.readObject() as String;
            _id = input.readObject() as int;
            _source = input.readObject() as int;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_bar_type);
            output.writeObject(_barcode);
            output.writeObject(_id);
            output.writeObject(_source);
        }
    }
}