/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (MailPackage.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class MailPackageBase extends AbstractEntity {

        public function MailPackageBase() {
            super();
        }

        private var _barcodes:ListCollectionView;
        private var _client_id:int;
        private var _delivery_id:int;
        private var _delivery_name:String;
        private var _execution_date:Date;
        private var _id:int;
        private var _id_name:String;
        private var _mail_service:int;
        private var _messages:ListCollectionView;
        private var _min_ord_state:int;
        private var _min_ord_state_name:String;
        private var _orders:ListCollectionView;
        private var _orders_num:int;
        private var _properties:ListCollectionView;
        private var _source:int;
        private var _source_code:String;
        private var _source_name:String;
        private var _src_date:Date;
        private var _src_state:int;
        private var _src_state_name:String;
        private var _state:int;
        private var _state_date:Date;
        private var _state_name:String;

        public function set barcodes(value:ListCollectionView):void {
            _barcodes = value;
        }
        public function get barcodes():ListCollectionView {
            return _barcodes;
        }

        public function set client_id(value:int):void {
            _client_id = value;
        }
        public function get client_id():int {
            return _client_id;
        }

        public function set delivery_id(value:int):void {
            _delivery_id = value;
        }
        public function get delivery_id():int {
            return _delivery_id;
        }

        public function set delivery_name(value:String):void {
            _delivery_name = value;
        }
        public function get delivery_name():String {
            return _delivery_name;
        }

        public function set execution_date(value:Date):void {
            _execution_date = value;
        }
        public function get execution_date():Date {
            return _execution_date;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set id_name(value:String):void {
            _id_name = value;
        }
        public function get id_name():String {
            return _id_name;
        }

        public function set mail_service(value:int):void {
            _mail_service = value;
        }
        public function get mail_service():int {
            return _mail_service;
        }

        public function set messages(value:ListCollectionView):void {
            _messages = value;
        }
        public function get messages():ListCollectionView {
            return _messages;
        }

        public function set min_ord_state(value:int):void {
            _min_ord_state = value;
        }
        public function get min_ord_state():int {
            return _min_ord_state;
        }

        public function set min_ord_state_name(value:String):void {
            _min_ord_state_name = value;
        }
        public function get min_ord_state_name():String {
            return _min_ord_state_name;
        }

        public function set orders(value:ListCollectionView):void {
            _orders = value;
        }
        public function get orders():ListCollectionView {
            return _orders;
        }

        public function set orders_num(value:int):void {
            _orders_num = value;
        }
        public function get orders_num():int {
            return _orders_num;
        }

        public function set properties(value:ListCollectionView):void {
            _properties = value;
        }
        public function get properties():ListCollectionView {
            return _properties;
        }

        public function set source(value:int):void {
            _source = value;
        }
        public function get source():int {
            return _source;
        }

        public function set source_code(value:String):void {
            _source_code = value;
        }
        public function get source_code():String {
            return _source_code;
        }

        public function set source_name(value:String):void {
            _source_name = value;
        }
        public function get source_name():String {
            return _source_name;
        }

        public function set src_date(value:Date):void {
            _src_date = value;
        }
        public function get src_date():Date {
            return _src_date;
        }

        public function set src_state(value:int):void {
            _src_state = value;
        }
        public function get src_state():int {
            return _src_state;
        }

        public function set src_state_name(value:String):void {
            _src_state_name = value;
        }
        public function get src_state_name():String {
            return _src_state_name;
        }

        public function set state(value:int):void {
            _state = value;
        }
        public function get state():int {
            return _state;
        }

        public function set state_date(value:Date):void {
            _state_date = value;
        }
        public function get state_date():Date {
            return _state_date;
        }

        public function set state_name(value:String):void {
            _state_name = value;
        }
        public function get state_name():String {
            return _state_name;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _barcodes = input.readObject() as ListCollectionView;
            _client_id = input.readObject() as int;
            _delivery_id = input.readObject() as int;
            _delivery_name = input.readObject() as String;
            _execution_date = input.readObject() as Date;
            _id = input.readObject() as int;
            _id_name = input.readObject() as String;
            _mail_service = input.readObject() as int;
            _messages = input.readObject() as ListCollectionView;
            _min_ord_state = input.readObject() as int;
            _min_ord_state_name = input.readObject() as String;
            _orders = input.readObject() as ListCollectionView;
            _orders_num = input.readObject() as int;
            _properties = input.readObject() as ListCollectionView;
            _source = input.readObject() as int;
            _source_code = input.readObject() as String;
            _source_name = input.readObject() as String;
            _src_date = input.readObject() as Date;
            _src_state = input.readObject() as int;
            _src_state_name = input.readObject() as String;
            _state = input.readObject() as int;
            _state_date = input.readObject() as Date;
            _state_name = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_barcodes);
            output.writeObject(_client_id);
            output.writeObject(_delivery_id);
            output.writeObject(_delivery_name);
            output.writeObject(_execution_date);
            output.writeObject(_id);
            output.writeObject(_id_name);
            output.writeObject(_mail_service);
            output.writeObject(_messages);
            output.writeObject(_min_ord_state);
            output.writeObject(_min_ord_state_name);
            output.writeObject(_orders);
            output.writeObject(_orders_num);
            output.writeObject(_properties);
            output.writeObject(_source);
            output.writeObject(_source_code);
            output.writeObject(_source_name);
            output.writeObject(_src_date);
            output.writeObject(_src_state);
            output.writeObject(_src_state_name);
            output.writeObject(_state);
            output.writeObject(_state_date);
            output.writeObject(_state_name);
        }
    }
}