/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (OrderExtraInfo.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class OrderExtraInfoBase extends AbstractEntity {

        public function OrderExtraInfoBase() {
            super();
        }

        private var _bookThickness:Number;
        private var _book_part:int;
        private var _book_type:int;
        private var _books:int;
        private var _calcAlias:String;
        private var _calcTitle:String;
        private var _calc_type:String;
        private var _corner_type:String;
        private var _cover:String;
        private var _coverMaterial:String;
        private var _dateIn:Date;
        private var _dateOut:Date;
        private var _endpaper:String;
        private var _format:String;
        private var _id:String;
        private var _interlayer:String;
        private var _kaptal:String;
        private var _messagesLog:ListCollectionView;
        private var _paper:String;
        private var _remark:String;
        private var _sheets:int;
        private var _sub_id:String;
        private var _weight:int;

        public function set bookThickness(value:Number):void {
            _bookThickness = value;
        }
        public function get bookThickness():Number {
            return _bookThickness;
        }

        public function set book_part(value:int):void {
            _book_part = value;
        }
        public function get book_part():int {
            return _book_part;
        }

        public function set book_type(value:int):void {
            _book_type = value;
        }
        public function get book_type():int {
            return _book_type;
        }

        public function set books(value:int):void {
            _books = value;
        }
        public function get books():int {
            return _books;
        }

        public function set calcAlias(value:String):void {
            _calcAlias = value;
        }
        public function get calcAlias():String {
            return _calcAlias;
        }

        public function set calcTitle(value:String):void {
            _calcTitle = value;
        }
        public function get calcTitle():String {
            return _calcTitle;
        }

        public function set calc_type(value:String):void {
            _calc_type = value;
        }
        public function get calc_type():String {
            return _calc_type;
        }

        public function set corner_type(value:String):void {
            _corner_type = value;
        }
        public function get corner_type():String {
            return _corner_type;
        }

        public function set cover(value:String):void {
            _cover = value;
        }
        public function get cover():String {
            return _cover;
        }

        public function set coverMaterial(value:String):void {
            _coverMaterial = value;
        }
        public function get coverMaterial():String {
            return _coverMaterial;
        }

        public function set dateIn(value:Date):void {
            _dateIn = value;
        }
        public function get dateIn():Date {
            return _dateIn;
        }

        public function set dateOut(value:Date):void {
            _dateOut = value;
        }
        public function get dateOut():Date {
            return _dateOut;
        }

        public function set endpaper(value:String):void {
            _endpaper = value;
        }
        public function get endpaper():String {
            return _endpaper;
        }

        public function set format(value:String):void {
            _format = value;
        }
        public function get format():String {
            return _format;
        }

        public function set id(value:String):void {
            _id = value;
        }
        public function get id():String {
            return _id;
        }

        public function set interlayer(value:String):void {
            _interlayer = value;
        }
        public function get interlayer():String {
            return _interlayer;
        }

        public function set kaptal(value:String):void {
            _kaptal = value;
        }
        public function get kaptal():String {
            return _kaptal;
        }

        public function set messagesLog(value:ListCollectionView):void {
            _messagesLog = value;
        }
        public function get messagesLog():ListCollectionView {
            return _messagesLog;
        }

        public function set paper(value:String):void {
            _paper = value;
        }
        public function get paper():String {
            return _paper;
        }

        public function set remark(value:String):void {
            _remark = value;
        }
        public function get remark():String {
            return _remark;
        }

        public function set sheets(value:int):void {
            _sheets = value;
        }
        public function get sheets():int {
            return _sheets;
        }

        public function set sub_id(value:String):void {
            _sub_id = value;
        }
        public function get sub_id():String {
            return _sub_id;
        }

        public function set weight(value:int):void {
            _weight = value;
        }
        public function get weight():int {
            return _weight;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _bookThickness = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _book_part = input.readObject() as int;
            _book_type = input.readObject() as int;
            _books = input.readObject() as int;
            _calcAlias = input.readObject() as String;
            _calcTitle = input.readObject() as String;
            _calc_type = input.readObject() as String;
            _corner_type = input.readObject() as String;
            _cover = input.readObject() as String;
            _coverMaterial = input.readObject() as String;
            _dateIn = input.readObject() as Date;
            _dateOut = input.readObject() as Date;
            _endpaper = input.readObject() as String;
            _format = input.readObject() as String;
            _id = input.readObject() as String;
            _interlayer = input.readObject() as String;
            _kaptal = input.readObject() as String;
            _messagesLog = input.readObject() as ListCollectionView;
            _paper = input.readObject() as String;
            _remark = input.readObject() as String;
            _sheets = input.readObject() as int;
            _sub_id = input.readObject() as String;
            _weight = input.readObject() as int;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_bookThickness);
            output.writeObject(_book_part);
            output.writeObject(_book_type);
            output.writeObject(_books);
            output.writeObject(_calcAlias);
            output.writeObject(_calcTitle);
            output.writeObject(_calc_type);
            output.writeObject(_corner_type);
            output.writeObject(_cover);
            output.writeObject(_coverMaterial);
            output.writeObject(_dateIn);
            output.writeObject(_dateOut);
            output.writeObject(_endpaper);
            output.writeObject(_format);
            output.writeObject(_id);
            output.writeObject(_interlayer);
            output.writeObject(_kaptal);
            output.writeObject(_messagesLog);
            output.writeObject(_paper);
            output.writeObject(_remark);
            output.writeObject(_sheets);
            output.writeObject(_sub_id);
            output.writeObject(_weight);
        }
    }
}